enum TimesOfDay {
    MORNING_CIVIL_TWILIGHT,
    MORNING_NAUTICAL_TWILIGHT,
    MORNING_ASTRONOMICAL_TWILIGHT,
    DAY,
    SUNRISE,
    EVENING_CIVIL_TWILIGHT,
    EVENING_NAUTICAL_TWILIGHT,
    EVENING_ASTRONOMICAL_TWILIGHT,
    SUNSET,
    NIGHT,
}

export default TimesOfDay;
